// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lspxekrpqgutlzeqbjsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzcHhla3JwcWd1dGx6ZXFianNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzMDg1MzQsImV4cCI6MjA3NDg4NDUzNH0.uYS63wBYH_gtFo4b3I3NvwINFv-HxkeQAqriTLLT8jQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});